force stop

diff --git a/sbin/_control b/sbin/_control
--- a/sbin/_control
+++ b/sbin/_control
@@ -16,9 +16,12 @@ export EVA_DIR EVA_CONTROLLER
 
 source <(./sbin/key-as-source config/uc:service CONTROLLER 2>/dev/null)
 
-if [ -z "$CONTROLLER_ENABLED" ]; then
-  echo "Unable to read registry key"
-  exit 1
+if [ "$FORCE_ALL" == "1" ]; then
+  CONTROLLER_ENABLED=1
+  if [ -z "$CONTROLLER_ENABLED" ]; then
+    echo "Unable to read registry key"
+    exit 1
+  fi
 fi
 
 
diff --git a/sbin/eva-control b/sbin/eva-control
--- a/sbin/eva-control
+++ b/sbin/eva-control
@@ -11,11 +11,16 @@ source <(./sbin/key-as-source config/uc:service UC 2>/dev/null)
 source <(./sbin/key-as-source config/lm:service LM 2>/dev/null)
 source <(./sbin/key-as-source config/sfa:service SFA 2>/dev/null)
 
-if [ -z "$UC_ENABLED" ] || [ -z "${LM_ENABLED}" ] || [ -z "${SFA_ENABLED}" ]; then
-  echo "Unable to read registry key"
-  exit 1
+if [ "${FORCE_ALL}" == "1" ]; then
+  UC_ENABLED=1
+  LM_ENABLED=1
+  SFA_ENABLED=1
+else
+  if [ -z "$UC_ENABLED" ] || [ -z "${LM_ENABLED}" ] || [ -z "${SFA_ENABLED}" ]; then
+    echo "Unable to read registry key"
+    exit 1
+  fi
 fi
-
 
 function controller_cmd() {
   c=${1,,}
